### ISSUE TITLE
Feature request: if no features.tsv file found scan for features.csv

### ISSUE THREAD

**Issue by waterfleas** [mbaityje/plankifier#6]
When previously classified folders are being reprocessed the features.tsv file is no longer available - but a csv file (features.csv) is available.
Could you put a switch in so features.tsv (raw from spcconvert, with sep = "\t") or features.csv (previously processed by enduser with sep = ",") will both work.  That would be great!

current code calling features.tsv is at src/helper_data.py 
L226  dftemp = pd.read_csv(datapaths[idp]+c+'/features.tsv', sep = '\t')

**Comment by kspruthviraj** [comment]
Thank you for the feature request. I have now added this feature to read *.csv files as well for mixed models.
