### ISSUE TITLE
Feature request: Skip jpeg on ResizeWithProportions error

### ISSUE THREAD

**Issue by waterfleas** [mbaityje/plankifier#7]
Hi Sreenath, another feature request.

When images are too narrow for transformation, ResizeWithProportions fails with error:
Traceback (most recent call last):
  File "predict.py", line 367, in <module>
    verbose=args.verbose,
  File "predict.py", line 157, in __init__
    self.npimages[L] = hd.LoadImageList(self.im_names, L,resize_images, show=False) # Load
  File "/redacted/plankifier-1.2.2/src/helper_data.py", line 519, in LoadImageList
    npimage,rescaled,filename=LoadImage(im_name,L,resize_images, show)
  File "/redacted/plankifier-1.2.2/src/helper_data.py", line 377, in LoadImage
    image,rescaled = ResizeWithProportions(image, L) # width and height are assumed to be the same (assertion at the beginning)
  File "/redacted/plankifier-1.2.2/src/helper_data.py", line 136, in ResizeWithProportions
    raise ValueError('Images are too extreme rectangles to be reduced to this size. Try increasing the desired image size.')
ValueError: Images are too extreme rectangles to be reduced to this size. Try increasing the desired image size.

This prevents prediction for the entire folder of images.  
Any chance you could implement a trycatch to skip the offending image and write to a log of skipped images?

**Comment by waterfleas** [comment]
I emailed you a tar.gz with an example

**Comment by kspruthviraj** [comment]
Hi Stuart,
Sure, I will look in to this issue.

**Comment by kspruthviraj** [comment]
I have updated the script and the issue has been resolved.
